dist: trusty
sudo: required
language: c
compiler: gcc
script: scripts/gen_appimage.sh
deploy:
  provider: releases
  file: "*.AppImage"
  file_glob: true
  skip_cleanup: true
  api_key:
    # @yuntan's GitHub API token
    secure: wP4GuTvFPkKHvnV8uGhByeY6jx6PNhWH71eHshnDMc8B15X4BuiMJvlqyVy22gektUAgKGjBY3aso0Ef6XfD/Qol1ud8lZxBllngBNa3p17PkN3b11YM2hcdzmD0lQVDWAksT2OiQe646FMoEfE6T5z6v6qvbtN1sDImwakKzjTFZXBDpcETF7jFRTIXBqqbp5azIJR+F0SEdTgo4l2CxCmOjYMdtj2r9EEOs9KEmhCLUp+pbPjugdKyOHltMCAxZHRsQMGS8KP1zEj3mkdywDs1Z0itZd9MKB0PHccuX/nkHVxucD0Nt8b+gnz3KmufpYTXaeQHkya+LTUM6fjIYC+J5KkEoF5pNtpjzOvDPNd9dlKV1QuMZdp9PvClJFyGbljaa7FvoomUZy6uX+PNfHdwr5K2vZwlJ2gokvbhrd7D1mQlRX/0TA+wHvv3+4j30/J0jvJ/9EM7MYZv4VQYzcN/sLvA1w6sWSnizAARXkM7hwdoYTorMBK662hNzgMATlRxcQu7WKxJir8zwSWvhCGfAUcKXs7p6WvKqC9OvhQlO99yGKIMn7kTm2XkvPcQrc4Zo3QcKqoWTZ+ogrKd+dmL5ndzsmD4UayUmM1dO7gfhYdPllfKauLOWxzo3LEGW+3flxD53z5yFaityxEW+LbA9dQFT5vhmWnL3F88qK0=
